Fixed problem with downloading data when user was null
kotlinx.serialization.MissingFieldException: Field 'user' is required, but it was missing
- changed  type User to optional